import { Link } from "react-router-dom";
import { BrainCircuit, ArrowRight, Sparkles, Zap, Target, Clock } from "lucide-react";

export default function AIRecommendation({ analytics = {} }) {
  const rec = analytics.recommendation ?? {
    title:         "Focus on Writing Task 2",
    description:   "Your Reading and Listening scores are excellent. Improving Coherence & Cohesion and Lexical Resource in Writing Task 2 can push your overall band to 8.0.",
    priority:      "High Priority",
    estimatedGain: "+0.5 Band",
    studyTime:     "30 mins/day",
  };

  const tips = [
    { icon: <Zap size={14} />, text: rec.estimatedGain,  color: "#f97316", bg: "rgba(249,115,22,.10)"  },
    { icon: <Clock size={14} />, text: rec.studyTime,    color: "#22d3a5", bg: "rgba(34,211,165,.10)" },
    { icon: <Target size={14} />, text: rec.priority,    color: "#4f8ef7", bg: "rgba(79,142,247,.10)"  },
  ];

  return (
    <section className="dashboard-section">
      <div className="section-header">
        <div>
          <h2>AI Recommendation</h2>
          <p>Personalised suggestions generated by Knarrow AI.</p>
        </div>
      </div>

      <div className="ai-card">
        <div className="ai-icon">
          <BrainCircuit size={42} />
        </div>

        <div className="ai-content">
          <h3>{rec.title}</h3>
          <p>{rec.description}</p>

          <div className="ai-meta">
            {tips.map((t, i) => (
              <div
                key={i}
                className="ai-pill"
                style={{ background: t.bg, color: t.color, borderColor: t.color + "33" }}
              >
                {t.icon}
                {t.text}
              </div>
            ))}
          </div>

          <Link to="/insights?tab=Goals">
            <button className="primary-btn">
              View Full Plan
              <ArrowRight size={18} />
            </button>
          </Link>
        </div>
      </div>
    </section>
  );
}
