import { Link } from "react-router-dom";
import {
  BrainCircuit,
  ArrowRight,
  Sparkles,
} from "lucide-react";

export default function AIRecommendation({
  analytics = {},
}) {

  const recommendation =
    analytics.recommendation ??
    {
      title: "Focus on Grammar Accuracy",
      description:
        "Your Reading and Listening performance is excellent. Improving Grammar Range & Accuracy and Task Response can significantly increase your Writing band score.",
      priority: "High Priority",
      estimatedGain: "+0.5 Band",
      studyTime: "30 mins",
    };

  return (

    <section className="dashboard-section">

      <div className="section-header">

        <div>

          <h2>

            AI Recommendation

          </h2>

          <p>

            Personalized suggestions generated by NextBand AI.

          </p>

        </div>

      </div>

      <div className="ai-card">

        <div className="ai-icon">

          <BrainCircuit size={42} />

        </div>

        <div className="ai-content">

          <h3>

            {recommendation.title}

          </h3>

          <p>

            {recommendation.description}

          </p>

          <div className="ai-meta">

            <div className="ai-pill">

              <Sparkles size={15} />

              {recommendation.priority}

            </div>

            <div className="ai-pill">

              🚀 {recommendation.estimatedGain}

            </div>

            <div className="ai-pill">

              ⏱ {recommendation.studyTime}

            </div>

          </div>

          <Link to="/ai-center">

            <button className="primary-btn">

              Open AI Coach

              <ArrowRight size={18} />

            </button>

          </Link>

        </div>

      </div>

    </section>

  );

}